blank_issues_enabled: false
contact_links:
  - name: Ask for support or share your ideas.
    url: https://github.com/dimpen/cloudflare-ddns-next/discussions/new/choose
    about: Please create a discussion.